// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTUUOlkNZ0NhIXdCc_4zDAt4XK7j2wHo',
    appId: '1:1097031950723:web:dc1eb06b49b4f17ef856b6',
    messagingSenderId: '1097031950723',
    projectId: 'ai-demo-2fea7',
    authDomain: 'ai-demo-2fea7.firebaseapp.com',
    storageBucket: 'ai-demo-2fea7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvRxZlozvUrszqhHGbtXpU37b3lcoXdVs',
    appId: '1:1097031950723:android:ed696545462b81d2f856b6',
    messagingSenderId: '1097031950723',
    projectId: 'ai-demo-2fea7',
    storageBucket: 'ai-demo-2fea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1f9IfT-aAoGmJZbglmDjX5SkNzAkteKA',
    appId: '1:1097031950723:ios:5c727224ab046c6cf856b6',
    messagingSenderId: '1097031950723',
    projectId: 'ai-demo-2fea7',
    storageBucket: 'ai-demo-2fea7.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1f9IfT-aAoGmJZbglmDjX5SkNzAkteKA',
    appId: '1:1097031950723:ios:5c727224ab046c6cf856b6',
    messagingSenderId: '1097031950723',
    projectId: 'ai-demo-2fea7',
    storageBucket: 'ai-demo-2fea7.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATTUUOlkNZ0NhIXdCc_4zDAt4XK7j2wHo',
    appId: '1:1097031950723:web:bf6df430d06385fcf856b6',
    messagingSenderId: '1097031950723',
    projectId: 'ai-demo-2fea7',
    authDomain: 'ai-demo-2fea7.firebaseapp.com',
    storageBucket: 'ai-demo-2fea7.firebasestorage.app',
  );
}